### ISSUE TITLE
Design switcher not visible

### ISSUE THREAD

**Issue by narko** [google/automotive-design-compose#154]
The following instructions cannot be followed right now:

```
Next, switch the app to use your copy of the Tutorial file by clicking the dropdown arrow in the upper right. This will open the Design Switcher.

Click the Change button to switch document IDs, and enter the ID of your copy of the Tutorial Figma File. Click Load and the app will start fetching your file (it'll take about a minute)
```

Somehow, the design switcher is not shown, unless you replace the id with your Figma file id beforehand:
```
@DesignDoc(id = "3z4xExq0INrL9vxPhj9tl7", version = "0.8")
```

See [tutorial/MainActivity.kt#L81](https://github.com/google/automotive-design-compose/blob/main/reference-apps/tutorial/app/src/main/java/com/android/designcompose/tutorial/MainActivity.kt#L81)

**Comment by timothyfroehlich** [comment]
Thanks for the report, please keep them coming! I believe this issue should have been fixed by #149, which was merged in yesterday. The root cause is some permissions issues with the Tutorial Figma File. We're planning on cutting a release candidate that will include the fix tomorrow. I'll leave this open until then, hopefully you'll have a chance to try it out and let us know if that solved it.

**Comment by narko** [comment]
Thanks @timothyfroehlich! I just had a look with the changes in `main`. Now I am able to see the Design switcher with the change button.
Unfortunately, when loading it, I still cannot see my own file. They only way is to change the id in `DesignDoc`.

A potential improvement: given the length of the figma ids, would it make sense to maybe set up the project to read this from a gradle local property?
Probably the same would make sense for the figma token.

**Comment by timothyfroehlich** [comment]
It's something we've thought about for sure. I'm working on the design for a few changes that should help here, but we know that it's a bit of a pain point.
