### ISSUE TITLE
Tutorial App crash due to Auto content widget setting

### ISSUE THREAD

**Issue by timothyfroehlich** [google/automotive-design-compose#82]
```
Live update for jVzAYF6 fetched and informed 31 subscribers
--------- beginning of crash
2023-05-19 16:17:13.619  8102-8102  AndroidRuntime          com.android.designcompose.tutorial   D  Shutting down VM
2023-05-19 16:17:13.624  8102-8102  AndroidRuntime          com.android.designcompose.tutorial   E  FATAL EXCEPTION: main
                                                                                                    Process: com.android.designcompose.tutorial, PID: 8102
                                                                                                    java.lang.IllegalStateException: Vertically scrollable component was measured with an infinity maximum height constraints, which is disallowed. One of the common reasons is nesting layouts like LazyColumn and Column(Modifier.verticalScroll()). If you want to add a header before the list of items please add a header as a separate item() before the main items() inside the LazyColumn scope. There are could be other reasons for this to happen: your ComposeView was added into a LinearLayout with some weight, you applied Modifier.wrapContentSize(unbounded = true) or wrote a custom layout. Please try to remove the source of infinite constraints in the hierarchy above the scrolling container.
                                                                                                    	at androidx.compose.foundation.CheckScrollableContainerConstraintsKt.checkScrollableContainerConstraints-K40F9xA(CheckScrollableContainerConstraints.kt:35)
                                                                                                    	at androidx.compose.foundation.ScrollingLayoutModifier.measure-3p2s80s(Scroll.kt:336)
                                                                                                    	at androidx.compose.ui.node.BackwardsCompatNode.measure-3p2s80s(BackwardsCompatNode.kt:323)
                                                                                                    	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:155)
```

Widget settings:
![image](https://github.com/google/automotive-design-compose/assets/5819722/b6bd728b-f2cf-450c-9b69-6eb8fa979109)

Re-opening the app seems to have fixed the problem, I haven't been able to reproduce it.

**Comment by iamralpht** [comment]
@rylin8 assigning this to you to validate, since we fixed something similar recently and this may not repro now.

**Comment by rylin8** [comment]
Tested and verified no crash. This was fixed in https://team-review.git.corp.google.com/c/aae-design-compose/design-compose/+/1835817

**Comment by timothyfroehlich** [comment]
I just reproduced it again with 0.20.0-rc01. Not sure why but this is still happening.

I was working through the tutorial to test 0.20.0 and followed the steps in Auto content widget 4. As soon as I changed the formatting to "Hug Contents" the app crashed, same error.

**Comment by timothyfroehlich** [comment]
And now the app is crashing every time I go to page 4. I've saved the serialized file and [this is the doc](https://www.figma.com/file/3z4xExq0INrL9vxPhj9tl7/branch/nqQmBbRp4Pv7r61TzXj30n). I'm not going to make any more modifications to it so we can reproduce the crash. I'm using the widget from the [0.20.0-rc01](https://github.com/google/automotive-design-compose/releases/tag/v0.20.0-rc01) release.

In case it matters, I built and launched the Tutorial using the main Gradle project, not the standalone Tutorial project.

**Comment by rylin8** [comment]
I was able to reproduce this with that doc, but if I create a new widget -- I tried both the published version and my development version -- it doesn't crash. My guess is that the widget in the tutorial project is old, so that when you click on it,  the old published version launches. I think we can fix this by deleting the widget in the Figma doc and creating another one with the latest published version. Any objections?

**Comment by timothyfroehlich** [comment]
I think that works. We should have the widget display a version number or
something like that so we know if it's out of date.

**Comment by rylin8** [comment]
Added https://github.com/google/automotive-design-compose/issues/130 to display a version number.
Tutorial Figma doc updates are done. We need to wait until @aubreydagoog removes the dials & gauges section and then we can republish the doc.

**Comment by aubreydagoog** [comment]
It was removed and put into a branch.

**Comment by rylin8** [comment]
@timothyfroehlich can you republish the tutorial?

**Comment by timothyfroehlich** [comment]
Just did.
